version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
     APP_NAME: cari-kuy
    expose:
      - 8080

  next:
    build: ./next
    container_name: next
    restart: always
    expose:
      - 3000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/cari-quy.glennprays.tech/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/cari-quy.glennprays.tech/privkey.pem:/etc/nginx/certs/privkey.pem
    ports:
      - 80:80
      - 443:443